### PR TITLE
Add LRU cache to web3 provider 

### PR DESCRIPTION
**Pull request by AlexNi245**

### CODE REVIEW

**Review by malteish — COMMENTED** [review]
Where does this come from and why do we trust it to work without unit tests?

**Comment by AlexNi245** [comment]
> Where does this come from and why do we trust it to work without unit tests?

The cache is already used within Gashawk and tested there

**Comment by malteish** [comment]
> > Where does this come from and why do we trust it to work without unit tests?
> 
> The cache is already used within Gashawk and tested there

Why not take the tests from there and using them here, too? Also, adding a reference to the gashawk repo in comments would be a good idea.

**Review by malteish — APPROVED** [review]
nice!

**Pull request merged**
